name: Semantic release

on:
    push:
        branches:
            - main
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
               with:
                check-latest: true
            - name: Check Node Version
              run: node -v
            - name: Install dependencies
              run: npm install
            - name: Build app
              run: npm run build
            - name: Semantic release
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npx semantic-release
